In [1]:
from deltabase import delta

db:delta = delta.connect("local")

In [2]:
db.upsert(table="mytable", primary_key="id", data=[
    {"id":1, "name":"jim"},
    {"id":2, "name":"jam"},
    {"id":3, "name":"pim"},
    {"id":4, "name":"pam"},
])

---

In [3]:
%%sql

-- with the `%%sql` magic command we can seamlessly 
-- switch between python and sql for our data manipulation.

select * from mytable

shape: (4, 2)
┌─────┬──────┐
│ id  ┆ name │
│ --- ┆ ---  │
│ i64 ┆ str  │
╞═════╪══════╡
│ 1   ┆ jim  │
│ 2   ┆ jam  │
│ 3   ┆ pim  │
│ 4   ┆ pam  │
└─────┴──────┘

In [4]:
# data from the previous cell can be accessed with `_`
data = _
data

shape: (4, 2)
┌─────┬──────┐
│ id  ┆ name │
│ --- ┆ ---  │
│ i64 ┆ str  │
╞═════╪══════╡
│ 1   ┆ jim  │
│ 2   ┆ jam  │
│ 3   ┆ pim  │
│ 4   ┆ pam  │
└─────┴──────┘

In [5]:
%%sql --table newtable --key id

-- additionally you can specify a table name and key to 
-- automatically have your sql query register a table into
-- the local sql context

select * from mytable

shape: (4, 2)
┌─────┬──────┐
│ id  ┆ name │
│ --- ┆ ---  │
│ i64 ┆ str  │
╞═════╪══════╡
│ 1   ┆ jim  │
│ 2   ┆ jam  │
│ 3   ┆ pim  │
│ 4   ┆ pam  │
└─────┴──────┘

In [6]:
db.tables

['mytable', 'newtable']

---

`%%ai` magic also exists. 

installing `deltabase[ai]` and setting the `OPENAI_API_KEY` env variable will allow you to quickly ask question to an llm, adding in the context of your data's schema.

**OUTSIDE OF THE SCHEMA, AND YOUR MESSAGE, NO DATA IS OR EVER WILL BE PROVIDED TO THE LLM**

In [7]:
%%ai --debug
describe the data available to me.

```json
[
    {
        "role": "system",
        "content": "answer the user's question. below is the data they have access to.data can be accessed via sql.\n"
    },
    {
        "role": "system",
        "content": "here is the data available to the user.\n- mytable: {'id': <class 'int'>, 'name': <class 'str'>}\n- newtable: {'id': <class 'int'>, 'name': <class 'str'>}\n"
    },
    {
        "role": "user",
        "content": "describe the data available to me.\n"
    }
]
```